---
- hosts: all

  pre_tasks:
    - name: Update packages
      become: true
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == 'Archlinux'

  tasks:
    - import_tasks: tasks/packages.yml
      tags: ['packages']

    - import_tasks: tasks/keybinds.yml
      tags: ['keybinds']

    - import_tasks: tasks/misc.yml
      tags: ['misc']

    - import_tasks: tasks/shell.yml
      tags: ['shell']

    - import_tasks: tasks/terminal.yml
      tags: ['terminal']
