---
- name: Configure ZSH
  copy:
    src: files/zsh
    dest: "{{ ansible_env.HOME }}/.config/"

- name: ZSH - Change user shell to zsh
  become: yes
  user:
    name: "{{ansible_env.SUDO_USER}}"
    shell: /bin/zsh

- name: set zprofile
  copy:
    src: files/.zprofile
    dest: "{{ ansible_env.home }}"

- name: Set xinitrc
  copy:
    src: files/.xinitrc
    dest: "{{ ansible_env.home }}"

- name: Configure VIM
  copy:
    src: files/.vimrc
    dest: "{{ ansible_env.HOME }}"

